name: Surveillance
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10  # You can adjust this version based on your requirements
  - numpy       # NumPy for numerical computations
  - opencv      # OpenCV for video processing
  - pyaudio     # PyAudio for audio processing
  - pip         # To support additional pip installations
  - pip:
      - datetime  # Included as a pip install to ensure compatibility if needed
